import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import ToastProvider from "@/components/ToastProvider/ToastProvider";
import { SessionProvider } from "next-auth/react";
import { UserProvider } from "@/UserContext";
import { auth } from "@/lib/auth";
import {
  getFavorites,
  getWatchedMoviesList,
  getWatchlist,
} from "@/utils/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "CineHub",
    template: "%s | Cinehub",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  let favorites = [];
  let watchlist = [];
  let watchedMovies = [];

  if (session?.user) {
    // In parallel or sequence
    [favorites, watchlist, watchedMovies] = await Promise.all([
      getFavorites(session?.user?.email),
      getWatchlist(session?.user?.email),
      getWatchedMoviesList(session?.user?.email),
    ]);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ToastProvider>
            <UserProvider
              user={session?.user}
              initialFavMovies={JSON.parse(JSON.stringify(favorites))}
              initialWatchlistMovies={JSON.parse(JSON.stringify(watchlist))}
              initialWatchedMoviesList={JSON.parse(
                JSON.stringify(watchedMovies)
              )}
            >
              <Navbar />
              <div className="pageContent">{children}</div>
              <Footer />
            </UserProvider>
          </ToastProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
